version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: postgres_db
    env_file: .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql